package com.example.paintingshop.mapper;

import com.example.paintingshop.model.Demand;
import com.example.paintingshop.model.DemandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DemandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    long countByExample(DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int deleteByExample(DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int insert(Demand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int insertSelective(Demand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    List<Demand> selectByExampleWithBLOBsWithRowbounds(DemandExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    List<Demand> selectByExampleWithBLOBs(DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    List<Demand> selectByExampleWithRowbounds(DemandExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    List<Demand> selectByExample(DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    Demand selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") Demand record, @Param("example") DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Demand record, @Param("example") DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int updateByExample(@Param("record") Demand record, @Param("example") DemandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int updateByPrimaryKeySelective(Demand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Demand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demand
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int updateByPrimaryKey(Demand record);
}