package com.example.paintingshop.mapper;

import com.example.paintingshop.model.Enlist;
import com.example.paintingshop.model.EnlistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EnlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enlist
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    long countByExample(EnlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enlist
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int deleteByExample(EnlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enlist
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enlist
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int insert(Enlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enlist
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int insertSelective(Enlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enlist
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    List<Enlist> selectByExampleWithRowbounds(EnlistExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enlist
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    List<Enlist> selectByExample(EnlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enlist
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    Enlist selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enlist
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") Enlist record, @Param("example") EnlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enlist
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int updateByExample(@Param("record") Enlist record, @Param("example") EnlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enlist
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int updateByPrimaryKeySelective(Enlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enlist
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int updateByPrimaryKey(Enlist record);
}