package com.example.paintingshop.mapper;

import com.example.paintingshop.model.Paintings;
import com.example.paintingshop.model.PaintingsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PaintingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paintings
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    long countByExample(PaintingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paintings
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int deleteByExample(PaintingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paintings
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paintings
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int insert(Paintings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paintings
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int insertSelective(Paintings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paintings
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    List<Paintings> selectByExampleWithRowbounds(PaintingsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paintings
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    List<Paintings> selectByExample(PaintingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paintings
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    Paintings selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paintings
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") Paintings record, @Param("example") PaintingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paintings
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int updateByExample(@Param("record") Paintings record, @Param("example") PaintingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paintings
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int updateByPrimaryKeySelective(Paintings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paintings
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    int updateByPrimaryKey(Paintings record);
}