package com.example.paintingshop.model;

public class Demand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demand.id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demand.title
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demand.specifications
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private String specifications;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demand.creator
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demand.follow_count
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Integer followCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demand.gmt_create
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demand.gmt_modified
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demand.state
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demand.price
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demand.closing_date
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private String closingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demand.purpose
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private String purpose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demand.enlist_count
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Integer enlistCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demand.paintings_url
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private String paintingsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demand.description
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demand.id
     *
     * @return the value of t_demand.id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demand.id
     *
     * @param id the value for t_demand.id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demand.title
     *
     * @return the value of t_demand.title
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demand.title
     *
     * @param title the value for t_demand.title
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demand.specifications
     *
     * @return the value of t_demand.specifications
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public String getSpecifications() {
        return specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demand.specifications
     *
     * @param specifications the value for t_demand.specifications
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setSpecifications(String specifications) {
        this.specifications = specifications == null ? null : specifications.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demand.creator
     *
     * @return the value of t_demand.creator
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demand.creator
     *
     * @param creator the value for t_demand.creator
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demand.follow_count
     *
     * @return the value of t_demand.follow_count
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Integer getFollowCount() {
        return followCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demand.follow_count
     *
     * @param followCount the value for t_demand.follow_count
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setFollowCount(Integer followCount) {
        this.followCount = followCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demand.gmt_create
     *
     * @return the value of t_demand.gmt_create
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demand.gmt_create
     *
     * @param gmtCreate the value for t_demand.gmt_create
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demand.gmt_modified
     *
     * @return the value of t_demand.gmt_modified
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demand.gmt_modified
     *
     * @param gmtModified the value for t_demand.gmt_modified
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demand.state
     *
     * @return the value of t_demand.state
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demand.state
     *
     * @param state the value for t_demand.state
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demand.price
     *
     * @return the value of t_demand.price
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demand.price
     *
     * @param price the value for t_demand.price
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demand.closing_date
     *
     * @return the value of t_demand.closing_date
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public String getClosingDate() {
        return closingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demand.closing_date
     *
     * @param closingDate the value for t_demand.closing_date
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setClosingDate(String closingDate) {
        this.closingDate = closingDate == null ? null : closingDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demand.purpose
     *
     * @return the value of t_demand.purpose
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demand.purpose
     *
     * @param purpose the value for t_demand.purpose
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose == null ? null : purpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demand.enlist_count
     *
     * @return the value of t_demand.enlist_count
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Integer getEnlistCount() {
        return enlistCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demand.enlist_count
     *
     * @param enlistCount the value for t_demand.enlist_count
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setEnlistCount(Integer enlistCount) {
        this.enlistCount = enlistCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demand.paintings_url
     *
     * @return the value of t_demand.paintings_url
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public String getPaintingsUrl() {
        return paintingsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demand.paintings_url
     *
     * @param paintingsUrl the value for t_demand.paintings_url
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setPaintingsUrl(String paintingsUrl) {
        this.paintingsUrl = paintingsUrl == null ? null : paintingsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demand.description
     *
     * @return the value of t_demand.description
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demand.description
     *
     * @param description the value for t_demand.description
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}