package com.example.paintingshop.model;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.notifier
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.receiver
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.outer_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long outerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.type
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.state
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.gmt_create
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.id
     *
     * @return the value of t_notification.id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.id
     *
     * @param id the value for t_notification.id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.notifier
     *
     * @return the value of t_notification.notifier
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.notifier
     *
     * @param notifier the value for t_notification.notifier
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.receiver
     *
     * @return the value of t_notification.receiver
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.receiver
     *
     * @param receiver the value for t_notification.receiver
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.outer_id
     *
     * @return the value of t_notification.outer_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getOuterId() {
        return outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.outer_id
     *
     * @param outerId the value for t_notification.outer_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setOuterId(Long outerId) {
        this.outerId = outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.type
     *
     * @return the value of t_notification.type
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.type
     *
     * @param type the value for t_notification.type
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.state
     *
     * @return the value of t_notification.state
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.state
     *
     * @param state the value for t_notification.state
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.gmt_create
     *
     * @return the value of t_notification.gmt_create
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.gmt_create
     *
     * @param gmtCreate the value for t_notification.gmt_create
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}