package com.example.paintingshop.model;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_number
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.demand_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long demandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.painter_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long painterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.state
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.price
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.gmt_create
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.gmt_modified
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.gmt_paid
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Integer gmtPaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.enlist_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long enlistId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_number
     *
     * @return the value of t_order.order_number
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_number
     *
     * @param orderNumber the value for t_order.order_number
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.demand_id
     *
     * @return the value of t_order.demand_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getDemandId() {
        return demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.demand_id
     *
     * @param demandId the value for t_order.demand_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setDemandId(Long demandId) {
        this.demandId = demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.painter_id
     *
     * @return the value of t_order.painter_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getPainterId() {
        return painterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.painter_id
     *
     * @param painterId the value for t_order.painter_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setPainterId(Long painterId) {
        this.painterId = painterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_id
     *
     * @return the value of t_order.customer_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.customer_id
     *
     * @param customerId the value for t_order.customer_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.state
     *
     * @return the value of t_order.state
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.state
     *
     * @param state the value for t_order.state
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.price
     *
     * @return the value of t_order.price
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.price
     *
     * @param price the value for t_order.price
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.gmt_create
     *
     * @return the value of t_order.gmt_create
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.gmt_create
     *
     * @param gmtCreate the value for t_order.gmt_create
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.gmt_modified
     *
     * @return the value of t_order.gmt_modified
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.gmt_modified
     *
     * @param gmtModified the value for t_order.gmt_modified
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.gmt_paid
     *
     * @return the value of t_order.gmt_paid
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Integer getGmtPaid() {
        return gmtPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.gmt_paid
     *
     * @param gmtPaid the value for t_order.gmt_paid
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setGmtPaid(Integer gmtPaid) {
        this.gmtPaid = gmtPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.enlist_id
     *
     * @return the value of t_order.enlist_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getEnlistId() {
        return enlistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.enlist_id
     *
     * @param enlistId the value for t_order.enlist_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setEnlistId(Long enlistId) {
        this.enlistId = enlistId;
    }
}