package com.example.paintingshop.model;

public class Paintings {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paintings.id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paintings.painter_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long painterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paintings.paintings_url
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private String paintingsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paintings.follow_count
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Integer followCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paintings.gmt_create
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paintings.gmt_modified
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paintings.type
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paintings.style
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private String style;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paintings.method
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    private String method;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paintings.id
     *
     * @return the value of t_paintings.id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paintings.id
     *
     * @param id the value for t_paintings.id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paintings.painter_id
     *
     * @return the value of t_paintings.painter_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getPainterId() {
        return painterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paintings.painter_id
     *
     * @param painterId the value for t_paintings.painter_id
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setPainterId(Long painterId) {
        this.painterId = painterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paintings.paintings_url
     *
     * @return the value of t_paintings.paintings_url
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public String getPaintingsUrl() {
        return paintingsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paintings.paintings_url
     *
     * @param paintingsUrl the value for t_paintings.paintings_url
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setPaintingsUrl(String paintingsUrl) {
        this.paintingsUrl = paintingsUrl == null ? null : paintingsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paintings.follow_count
     *
     * @return the value of t_paintings.follow_count
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Integer getFollowCount() {
        return followCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paintings.follow_count
     *
     * @param followCount the value for t_paintings.follow_count
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setFollowCount(Integer followCount) {
        this.followCount = followCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paintings.gmt_create
     *
     * @return the value of t_paintings.gmt_create
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paintings.gmt_create
     *
     * @param gmtCreate the value for t_paintings.gmt_create
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paintings.gmt_modified
     *
     * @return the value of t_paintings.gmt_modified
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paintings.gmt_modified
     *
     * @param gmtModified the value for t_paintings.gmt_modified
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paintings.type
     *
     * @return the value of t_paintings.type
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paintings.type
     *
     * @param type the value for t_paintings.type
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paintings.style
     *
     * @return the value of t_paintings.style
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paintings.style
     *
     * @param style the value for t_paintings.style
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paintings.method
     *
     * @return the value of t_paintings.method
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paintings.method
     *
     * @param method the value for t_paintings.method
     *
     * @mbg.generated Sun May 17 10:49:14 CST 2020
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }
}